In [4]:
import numpy as np
import pandas as pd
import torch

In [5]:
a = torch.tensor(1)  # 0d
a

tensor(1)

In [ ]:
b = torch.tensor([1, 2, 3])  # 1d
b

In [6]:
c = torch.tensor([[1, 2, 3], [4, 5, 6]]) # 2d
c

tensor([[1, 2, 3],
        [4, 5, 6]])

In [7]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [8]:
arr_tensor = torch.from_numpy(arr)
arr_tensor

tensor([1, 2, 3])

In [9]:
arr[0] = 5

In [10]:
arr_tensor

tensor([5, 2, 3])

In [11]:
a = torch.tensor(2, dtype=torch.float32, device='cpu', requires_grad=True)

In [12]:
a.tolist()

2.0

In [13]:
b = torch.tensor(3)

c = a**2
c = c + b
c

tensor(7., grad_fn=<AddBackward0>)

In [14]:
X = torch.arange(1, 201)  # числа від 1 до 200
X = torch.randn(200)   # нормально розподілені числа з середнім=0, стандартне відхилення: 1.5

In [15]:
c.backward()

In [16]:
a.grad

tensor(4.)

In [17]:
from torch import nn

loss_fn = nn.MSELoss()

In [18]:
X = torch.normal(22, 2, size=(200, )).reshape(-1, 1)  # середнє 22, стардатне відхилення 2
display(X.shape)

y = 2.0 * X + 3 + 0.1 * torch.randn(200, 1)
display(y.shape)

# параметр швидкості навчання
learning_rate = 0.01

history = []

# створюємо модель
model = nn.Linear(1, 1)

for epoch in range(21):
    # один крок тренування (пропускаємо X через модель)
    # рух вперед (forward)
    y_pred = model(X)

    # рахуємо помилку
    loss = loss_fn(y_pred, y)

    # рух назад
    loss.backward()

    with torch.no_grad():
        for param in model.parameters():
            param -= learning_rate * param.grad

    # обнулити градієнти
    model.zero_grad()

    history.append({
        "epoch": epoch,
        "loss": loss.item(),
        "weight": model.weight.item(),
        "bias": model.bias.item()
    })

history_df = pd.DataFrame(history)
history_df.head(10)

torch.Size([200, 1])

torch.Size([200, 1])

,epoch,loss,weight,bias
0,0,1.593375e+03,1.796904e+01,1.609430e+00
1,1,1.240090e+05,-1.379530e+02,-5.393686e+00
2,2,9.651699e+06,1.237618e+03,5.639367e+01
3,3,7.511985e+08,-1.089790e+04,-4.887003e+02
4,4,5.846629e+10,9.616372e+04,4.320216e+03
5,5,4.550472e+12,-8.483521e+05,-3.810486e+04
6,6,3.541663e+14,7.484326e+06,3.361763e+05
7,7,2.756500e+16,-6.602798e+07,-2.965796e+06
8,8,2.145402e+18,5.825100e+08,2.616476e+07
9,9,1.669782e+20,-5.139003e+09,-2.308300e+08


In [19]:
history_df.tail(10)

,epoch,loss,weight,bias
11,11,1.011489e+24,-3.999721e+11,-1.796565e+10
12,12,7.872492e+25,3.528622e+12,1.584961e+11
13,13,6.127214e+27,-3.113011e+13,-1.398279e+12
14,14,4.768855e+29,2.746351e+14,1.233586e+13
15,15,3.711631e+31,-2.422877e+15,-1.088291e+14
16,16,2.888788e+33,2.137504e+16,9.601083e+14
17,17,2.248364e+35,-1.885742e+17,-8.470239e+15
18,18,inf,1.663634e+18,7.472589e+16
19,19,inf,-1.467686e+19,-6.592446e+17
20,20,inf,1.294818e+20,5.815969e+18
