In [6]:
import numpy as np

In [7]:
matrix = np.arange(1, 25).reshape(4, 6)
matrix

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [8]:
matrix

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [9]:
new_matrix = matrix.reshape(3, 8)
new_matrix

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [10]:
min_values = new_matrix.min(axis=1)
max_values = new_matrix.max(axis=1)

min_values, max_values

(array([ 1,  9, 17]), array([ 8, 16, 24]))

In [11]:
total_sum = new_matrix.sum()
total_sum

np.int64(300)

In [12]:
import pandas as pd

In [13]:
df = pd.DataFrame({
    "Ім'я": ["Аня", "Богдан", "Іван", "Оля", "Марія", "Петро", "Софія", "Данило"],
    "Проект": ["AI", "Web", "AI", "ML", "Web", "ML", "AI", "Web"],
    "Години": [10, 15, 8, 20, 12, 7, 14, 9]
})

df

,Ім'я,Проект,Години
0,Аня,AI,10
1,Богдан,Web,15
2,Іван,AI,8
3,Оля,ML,20
4,Марія,Web,12
5,Петро,ML,7
6,Софія,AI,14
7,Данило,Web,9


In [14]:
df.groupby("Ім'я")["Години"].sum()

Ім'я
Іван       8
Аня       10
Богдан    15
Данило     9
Марія     12
Оля       20
Петро      7
Софія     14
Name: Години, dtype: int64

In [15]:
df.groupby("Проект")["Години"].sum()

Проект
AI     32
ML     27
Web    36
Name: Години, dtype: int64

In [17]:
hours_by_employee = df.groupby("Ім'я")["Години"].sum()

print("Співробітник:", hours_by_employee.idxmax())
print("Години:", hours_by_employee.max())

Співробітник: Оля
Години: 20
