In [1]:
print('Hello, World')

Hello, World


| Показник | Значення |
|:---------| :--- |
| Середнє  | 1.334 |

In [2]:
my_list = [1, 'text', True, []]
my_list

[1, 'text', True, []]

In [3]:
import numpy as np

In [7]:
import numpy as np

In [8]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [9]:
print(arr)

[1 2 3 4]


In [10]:
arr2 = np.arange(1, 10, 2)
arr2

array([1, 3, 5, 7, 9])

In [12]:
arr3 = np.array([1, 2, 120, 5000], dtype=np.int16)
arr3

array([   1,    2,  120, 5000], dtype=int16)

In [ ]:
arr6 = np.zeros(15)
arr6

In [ ]:
print(arr6[1:4])

In [17]:
arr7 = np.full(10, 7)
arr7

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [1]:
arr8 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr8

NameError: name 'np' is not defined

In [ ]:
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

image = np.array(Image.open("../../data/cat.webp"))

print(image.shape)

# Візуалізація
plt.imshow(image)
plt.axis("off")
plt.show()

In [ ]:
contrast_factor = 2
less_contrast = np.clip(image / contrast_factor, 0, 255).astype(np.uint8)

In [ ]:
# Візуалізація
plt.imshow(less_contrast)
plt.axis("off")
plt.show()

In [2]:
np.min(arr4)

NameError: name 'np' is not defined

In [ ]:
np.min(arr8, axis=1)

In [ ]:
np.mean(arr8, axis=0)

In [ ]:
np.sum(arr8)

In [ ]:
np.sort(arr4)[::-1]

In [ ]:
arr4 < 20

In [ ]:
arr8 = arr8.flatten()
arr8

In [ ]:
arr8 = arr8.reshape((3, 3, 1))
arr8

### Завдання 1

1. Створіть одновимірний масив із 10 випадкових чисел від 0 до 100.
2. Збережіть масив у змінну і виведіть його на екран.
3. Знайдіть мінімальне, максимальне та середнє значення масиву за допомогою вбудованих функцій NumPy.
4. Відсортуйте масив за зростанням і виведіть результат.

In [18]:
arr = np.random.randint(0, 101, 10)

In [19]:
print("Масив:", arr)

Масив: [74 30 78 17 22  5 85 39 82 22]


In [20]:
print("Мінімальне значення:", np.min(arr))
print("Максимальне значення:", np.max(arr))
print("Середнє значення:", np.mean(arr))

Мінімальне значення: 5
Максимальне значення: 85
Середнє значення: 45.4


In [21]:
sorted_arr = np.sort(arr)
print("Відсортований масив:", sorted_arr)

Відсортований масив: [ 5 17 22 22 30 39 74 78 82 85]


In [ ]:
import pandas as pd
import numpy as np