In [ ]:
print('Hello, World!')

| Показник  |   Значення   |
|-----------|:------------:|
| Середнє   |    1.334     |


## Header 2

* item 1

In [11]:
my_list = [1, 2, 3, 4]
print(my_list)

[1, 2, 3, 4]


In [8]:
import numpy as np

In [9]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [12]:
print(arr)

[1 2 3 4]


In [13]:
arr2 = np.arange(1, 10, 2)
arr2

array([1, 3, 5, 7, 9])

In [19]:
arr3 = np.array([1, 2, 127], dtype=np.int8)
arr3

array([  1,   2, 127], dtype=int8)

In [22]:
arr3 = np.array([1, 2, 127])
arr3.dtype

dtype('int64')

In [23]:
arr4 = np.random.randint(1, 100, 10)

arr4

array([96, 93, 54, 60, 66, 46, 15, 91, 18, 80], dtype=int32)

In [24]:
arr5 = np.ones(10)
arr5

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
arr6 = np.zeros(15)
arr6

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
print(arr6[1:4])

[0. 0. 0.]


In [29]:
arr7 = np.full(10,  7)
arr7

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [32]:
arr7.shape

(10,)

In [30]:
arr8 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr8

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr8.shape

(3, 3)

In [34]:
np.min(arr4)

np.int32(15)

In [37]:
np.min(arr8, axis=1)

array([1, 4, 7])

In [39]:
np.mean(arr8, axis=0)

array([4., 5., 6.])

In [40]:
np.sum(arr8)

np.int64(45)

In [61]:
np.sort(arr4)

array([15, 18, 46, 54, 60, 66, 80, 91, 93, 96], dtype=int32)

In [45]:
arr4

array([96, 93, 54, 60, 66, 46, 15, 91, 18, 80], dtype=int32)

In [46]:
arr4[arr4 < 20]

array([15, 18], dtype=int32)

In [47]:
arr4 < 20

array([False, False, False, False, False, False,  True, False,  True,
       False])

In [48]:
arr8

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
arr8 = arr8.flatten()
arr8

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr8 = arr8.reshape((3, 3, 1))
arr8

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

### Завдання 1

1. Створіть одновимірний масив із 10 випадкових чисел від 0 до 100.
2. Збережіть масив у змінну і виведіть його на екран.
3. Знайдіть мінімальне, максимальне та середнє значення масиву за допомогою вбудованих функцій NumPy.
4. Відсортуйте масив за зростанням і виведіть результат.